version: '2'

services:
  web:
    build: web
    image: dockercon16-aspnet-frontend
    volumes: ["./web/static:/usr/share/nginx/html"]
    ports: ["80:80"]
  words-api:
    build: 
      context: publish/words-aspnet
      dockerfile: Dockerfile.run
    image: dockercon16-aspnet-backend:optimized
    # ports: ["5000:80"]
